<a href="https://colab.research.google.com/github/ZuhairHossain/Psychological-Aspect-of-Cancer-Patients/blob/master/Pre_Thesis_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [644]:
# data labelling done till MaritalStatus

In [645]:
import pandas as pd
import io
import numpy as np
import sklearn

In [646]:
df = pd.read_csv("https://raw.githubusercontent.com/ZuhairHossain/Psychological-Aspect-of-Cancer-Patients/master/cancer_manual_data.csv")

pd.set_option('display.max_columns', None)
df.head()

PatientName       DataCollectionPlace    Age Gender CurrentAddress  \
0        Nurul Islam  Hospitals Doctor Chamber    65+   Male    Kishoregonj   
1         Md. Rafian  Hospitals Doctor Chamber    65+   Male     Jhalokathi   
2          Rojob Ali  Hospitals Doctor Chamber  45-64   Male        Tangail   
3     Ismail Hossain  Hospitals Doctor Chamber  25-44   Male            NaN   
4  Md. Golam Mostafa             Hospital Ward  45-64   Male        Cumilla   

  Education   Profession Religion MaritalStatus  TotalChildCount  GirlChild  \
0      <SSC       Farmer    Islam       Married                4        1.0   
1       SSC  Shop Keeper    Islam       Married                1        1.0   
2      <SSC  House Works    Islam       Widowed                5        1.0   
3      <SSC   CNG Driver    Islam       Married                0        NaN   
4       SSC      Retired    Islam       Married                3        1.0   

   BoyChild   MonthlyEarning CancerType  CancerStage AdmittedHospital  \
0       3.0  Less than 20.6k       Anal            3              Yes   
1       0.0  Less than 20.6k      Blood            1              Yes   
2       4.0  Less than 20.6k     Throat            3              Yes   
3       NaN  Less than 20.6k     Throat            3              Yes   
4       2.0  Less than 20.6k      Lungs            3              Yes   

  Operation FamilyMemberCancer FamMemSupport HospitalFeesPaymentIssue Loan  \
0       Yes                 No           Yes                Sometimes  Yes   
1        No                 No           Yes         Almost Regularly  Yes   
2        No                 No           Yes         Almost Regularly   No   
3       Yes                Yes           Yes                Regularly  Yes   
4       Yes                 No           Yes                Regularly  Yes   

  ElectronicDeviceforContact ElectronicDeviceType ContactDeviceWithDoctor  \
0                         No                  NaN              Not at all   
1                        Yes           Smartphone               Sometimes   
2                        Yes        Button Mobile              Not at all   
3                        Yes        Button Mobile              Not at all   
4                        Yes        Button Mobile               Sometimes   

  InternetAccess InternetUseExperience InternetUseForCancer  \
0             No         No Experience           Not at all   
1            Yes                Senior           Not at all   
2             No         No Experience           Not at all   
3             No         No Experience           Not at all   
4             No         No Experience           Not at all   

     DataCollectedBy                     PHQ1                     PHQ2  \
0  Zuhair + Mrittika               Not at all  More than half the days   
1              Miami            Several\ndays        Nearly\nevery day   
2           Mrittika        Nearly\nevery day            Several\ndays   
3              Miami        Nearly\nevery day        Nearly\nevery day   
4             Zuhair  More than half the days  More than half the days   

                      PHQ3                     PHQ4                     PHQ5  \
0        Nearly\nevery day        Nearly\nevery day        Nearly\nevery day   
1               Not at all        Nearly\nevery day  More than half the days   
2            Several\ndays        Nearly\nevery day               Not at all   
3        Nearly\nevery day               Not at all            Several\ndays   
4  More than half the days  More than half the days        Nearly\nevery day   

                      PHQ6                     PHQ7                     PHQ8  \
0  More than half the days  More than half the days  More than half the days   
1        Nearly\nevery day        Nearly\nevery day        Nearly\nevery day   
2               Not at all               Not at all               Not at all   
3  More than half the days  More than half the days            

#Encoding Categorical values


In [647]:
df = df.drop(['PatientName'], axis=1)

In [648]:
df['DataCollectionPlace'].unique()

array(['Hospitals Doctor Chamber', 'Hospital Ward'], dtype=object)

In [649]:
df['DataCollectionPlace'] = df['DataCollectionPlace'].map({'Hospitals Doctor Chamber': 1, 'Hospital Ward':2})
print(df.DataCollectionPlace.unique())

[1 2]


In [650]:
df['Age'].unique()

array(['65+', '45-64', '25-44', '18-24'], dtype=object)

In [651]:
df['Age'] = df['Age'].map({'18-24': 1, '25-44':2, '45-64':3,'65+':4})
print(df.Age.unique())

[4 3 2 1]


In [652]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [653]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female':2})
print(df.Gender.unique())

[1 2]


In [654]:
df['CurrentAddress'].unique()

array(['Kishoregonj', 'Jhalokathi', 'Tangail', nan, 'Cumilla',
       'Gopalgonj', 'Jhinaidah', 'Barisal', 'Narayanginj', 'Dhaka',
       'Bogura', 'Feni', 'Sylhet', 'Tongi', 'Dinajpur', 'Thakurgaon',
       'Nilfamari', 'Rangamati', 'Pabna', 'Noakhali', 'Bhola', 'Jamalpur',
       'Narail', 'Kurigram', 'Chittagong', "Cox's Bazar", 'Mymensingh'],
      dtype=object)

In [655]:
df['Education'].unique()

array(['<SSC', 'SSC', 'HSC', 'Bachelor', 'Diploma', 'Ph.D', 'Masters'],
      dtype=object)

In [656]:
df['Education'] = df['Education'].map({'<SSC': 1, 'SSC':2, 'HSC':3,'Bachelor':4 ,'Diploma':5,'Ph.D':6,'Masters':7})
print(df.Education.unique())

[1 2 3 4 5 6 7]


In [657]:
df['Profession'].unique()

array(['Farmer', 'Shop Keeper', 'House Works', 'CNG Driver', 'Retired',
       'Small Business', 'House Wife', 'Teacher', 'Student', 'Job Holder',
       'Day Labour', 'Banker', 'Government Job', 'Large Business',
       'Defense'], dtype=object)

In [658]:
df['Profession'] = df['Profession'].map({'Farmer': 1, 'Shop Keeper':2, 'House Works':3,'CNG Driver':4 ,'Retired':5,'Small Business':6,
                                         'House Wife':7, 'Teacher':8, 'Student':9, 'Large Business':10,'Job Holder':11,
                                         'Day Labour':12, 'Banker':13, 'Government Job':14, 'Defense':15})
print(df.Education.unique())

[1 2 3 4 5 6 7]


In [659]:
df['Religion'].unique()

array(['Islam'], dtype=object)

In [660]:
df['Religion'] = df['Religion'].map({'Islam': 1})
print(df.Religion.unique())

[1]


In [661]:
df['MaritalStatus'].unique()

array(['Married', 'Widowed', 'Unmarried', 'Divorced'], dtype=object)

In [662]:
df['MaritalStatus'] = df['MaritalStatus'].map({'Married': 1, 'Unmarried':2, 'Widowed':3, 'Divorced':4})
print(df.MaritalStatus.unique())

[1 3 2 4]


In [663]:
df['CancerType'].unique()

array(['Anal', 'Blood', 'Throat', 'Lungs', 'Prostate', 'Breast',
       'Cervical', 'Ovary', 'Lip and Oral', 'Stomach', 'Liver', 'Bladder',
       'Leukomia'], dtype=object)

In [664]:
df['CancerType'] = df['CancerType'].map({'Anal': 1, 'Blood':2, 'Throat':3, 'Throat':4, 'Lungs':5, 'Prostate':6, 'Breast':7,
                                         'Cervical':8, 'Ovary':9, 'Lip and Oral':10, 'Stomach':11, 'Liver':12, 'Bladder':13,
                                         'Leukomia': 14})
print(df.CancerType.unique())

[ 1  2  4  5  6  7  8  9 10 11 12 13 14]


In [665]:
# for instance dropping this current address column, may use for later purpose
df=df.drop(['CurrentAddress', 'DataCollectedBy', 'AdmittedHospital','ElectronicDeviceforContact','ElectronicDeviceType','ContactDeviceWithDoctor',
            'InternetAccess', 'InternetUseExperience', 'PatientConfused', 'OurPurpose', 'PatientType', 'GirlChild', 'BoyChild'], axis=1)

In [666]:
df['MonthlyEarning'].unique()

array(['Less than 20.6k', '20.6K-51.6K', '51.6K+'], dtype=object)

In [667]:
df['MonthlyEarning'] = df['MonthlyEarning'].map({'Less than 20.6k': 1, '20.6K-51.6K':2, '51.6K+':3})
print(df.MaritalStatus.unique())

[1 3 2 4]


In [668]:
df['Operation'].unique()

array(['Yes', 'No'], dtype=object)

In [669]:
df['Operation'] = df['Operation'].map({'Yes': 0, 'No':1})
print(df.Operation.unique())

[0 1]


In [670]:
df['FamilyMemberCancer'].unique()

array(['No', 'Yes'], dtype=object)

In [671]:
df['FamilyMemberCancer'] = df['FamilyMemberCancer'].map({'Yes': 0, 'No':1})
print(df.FamilyMemberCancer.unique())

[1 0]


In [672]:
df['FamMemSupport'].unique()

array(['Yes', 'No'], dtype=object)

In [673]:
df['FamMemSupport'] = df['FamMemSupport'].map({'Yes': 0, 'No':1})
print(df.FamMemSupport.unique())

[0 1]


In [674]:
df['HospitalFeesPaymentIssue'].unique()

array(['Sometimes', 'Almost Regularly', 'Regularly', 'Little not',
       'Not at all'], dtype=object)

In [675]:
df['HospitalFeesPaymentIssue'] = df['HospitalFeesPaymentIssue'].map({'Sometimes': 3, 'Almost Regularly':4, 'Regularly':5, 'Little not':2, 'Not at all':1})
print(df.HospitalFeesPaymentIssue.unique())

[3 4 5 2 1]


In [676]:
df['Loan'] = df['Loan'].map({'Yes': 0, 'No':1})
print(df.Loan.unique())

[0 1]


In [677]:
df['InternetUseForCancer'].unique()

array(['Not at all', 'Sometimes', 'Almost Regularly', 'Regularly',
       'Little not'], dtype=object)

In [678]:
df['InternetUseForCancer'] = df['InternetUseForCancer'].map({'Sometimes': 3, 'Almost Regularly':4, 'Regularly':5, 'Little not':2, 'Not at all':1})
print(df.InternetUseForCancer.unique())

[1 3 4 5 2]


In [679]:
df['PHQ1'].unique()

array(['Not at all', 'Several\ndays', 'Nearly\nevery day',
       'More than half the days'], dtype=object)

In [680]:
df['PHQ1'] = df ['PHQ1'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ2'] = df ['PHQ2'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ3'] = df ['PHQ3'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ4'] = df ['PHQ4'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ5'] = df ['PHQ5'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ6'] = df ['PHQ6'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ7'] = df ['PHQ7'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ8'] = df ['PHQ8'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})
df['PHQ9'] = df ['PHQ9'].map({'Not at all':0, 'Several\ndays':1, 'Nearly\nevery day':2, 'More than half the days':3})

In [681]:
df['PHQ10'].unique()

array(['Tough', 'Not Tougher', 'Toughest', 'Tougher'], dtype=object)

In [682]:
df['PHQ10'] = df['PHQ10'].map({'Not Tougher': 1, 'Tough':2, 'Tougher':3, 'Toughest':4})
print(df.PHQ10.unique())

[2 1 4 3]


In [683]:
df['CancerInMyBody'] = df['CancerInMyBody'].map({'Yes': 0, 'No':1})
print(df.CancerInMyBody.unique())

[0 1]


In [684]:
phq9 = ['PHQ1','PHQ2','PHQ3','PHQ4','PHQ5','PHQ6','PHQ7','PHQ8','PHQ9']

df['PHQ9_Total'] = df[phq9].sum(axis = 1)

In [685]:
conditions = [(df['PHQ9_Total']>=0) & (df['PHQ9_Total']<=4),
              (df['PHQ9_Total']>=5) & (df['PHQ9_Total']<=9),
              (df['PHQ9_Total']>=10) & (df['PHQ9_Total']<=14),
              (df['PHQ9_Total']>=15) & (df['PHQ9_Total']<=19),
              (df['PHQ9_Total']>=20) & (df['PHQ9_Total']<=27)]
choices = ['None','Mild','Moderate','Moderately Severe','Severe']
df['Depression_lvl'] = np.select(conditions, choices, default = 'Cannot Identify')

In [686]:
conditions = [(df['Depression_lvl']=="None"),
              (df['Depression_lvl']=="Mild"),
              (df['Depression_lvl']=="Moderate"),
              (df['Depression_lvl']=="Moderately Severe"),
              (df['Depression_lvl']=="Severe")
              ]
choices = ['0','1','2','3','4']
df['Depression_lvl_2'] = np.select(conditions, choices, default = 'Cannot Identify')

In [687]:
df.head()

DataCollectionPlace  Age  Gender  Education  Profession  Religion  \
0                    1    4       1          1           1         1   
1                    1    4       1          2           2         1   
2                    1    3       1          1           3         1   
3                    1    2       1          1           4         1   
4                    2    3       1          2           5         1   

   MaritalStatus  TotalChildCount  MonthlyEarning  CancerType  CancerStage  \
0              1                4               1           1            3   
1              1                1               1           2            1   
2              3                5               1           4            3   
3              1                0               1           4            3   
4              1                3               1           5            3   

   Operation  FamilyMemberCancer  FamMemSupport  HospitalFeesPaymentIssue  \
0          0                   1              0                         3   
1          1                   1              0                         4   
2          1                   1              0                         4   
3          0                   0              0                         5   
4          0                   1              0                         5   

   Loan  InternetUseForCancer  PHQ1  PHQ2  PHQ3  PHQ4  PHQ5  PHQ6  PHQ7  PHQ8  \
0     0                     1     0     3     2     2     2     3     3     3   
1     0                     1     1     2     0     2     3     2     2     2   
2     1                     1     2     1     1     2     0     0     0     0   
3     0                     1     2     2     2     0     1     3     3     1   
4     0                     1     3     3     3     3     2     1     3     3   

   PHQ9  PHQ10  CancerInMyBody  PHQ9_Total     Depression_lvl Depression_lvl_2  
0     1      2               0          19  Moderately Severe                3  
1     0      1               1          14           Moderate                2  
2     0      1               1           6               Mild                1  
3     3      1               1          17  Moderately Severe                3  
4     0      2               1          21             Severe                4

In [688]:
df.to_csv('labelled_data.csv', index=False)

In [692]:
df2 = pd.read_csv('labelled_data.csv')
df2.isnull().sum()

DataCollectionPlace         0
Age                         0
Gender                      0
Education                   0
Profession                  0
Religion                    0
MaritalStatus               0
TotalChildCount             0
MonthlyEarning              0
CancerType                  0
CancerStage                 0
Operation                   0
FamilyMemberCancer          0
FamMemSupport               0
HospitalFeesPaymentIssue    0
Loan                        0
InternetUseForCancer        0
PHQ1                        0
PHQ2                        0
PHQ3                        0
PHQ4                        0
PHQ5                        0
PHQ6                        0
PHQ7                        0
PHQ8                        0
PHQ9                        0
PHQ10                       0
CancerInMyBody              0
PHQ9_Total                  0
Depression_lvl              0
Depression_lvl_2            0
dtype: int64