<a href="https://colab.research.google.com/github/ZuhairHossain/Psychological-Aspect-of-Cancer-Patients/blob/master/Pre_Thesis_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [110]:
# data labelling done till MaritalStatus

In [90]:
import pandas as pd
import io
import numpy as np
import sklearn

In [91]:
df = pd.read_csv("https://raw.githubusercontent.com/ZuhairHossain/Psychological-Aspect-of-Cancer-Patients/master/cancer_manual_data.csv")

pd.set_option('display.max_columns', None)
df.head()

PatientName       DataCollectionPlace    Age Gender CurrentAddress  \
0        Nurul Islam  Hospitals Doctor Chamber    65+   Male    Kishoregonj   
1         Md. Rafian  Hospitals Doctor Chamber    65+   Male     Jhalokathi   
2          Rojob Ali  Hospitals Doctor Chamber  45-64   Male        Tangail   
3     Ismail Hossain  Hospitals Doctor Chamber  25-44   Male            NaN   
4  Md. Golam Mostafa             Hospital Ward  45-64   Male        Cumilla   

  Education   Profession Religion MaritalStatus  TotalChildCount  GirlChild  \
0      <SSC       Farmer    Islam       Married              4.0        1.0   
1       SSC  Shop Keeper    Islam       Married              1.0        1.0   
2      <SSC  House Works    Islam       Widowed              5.0        1.0   
3      <SSC   CNG Driver    Islam       Married              NaN        NaN   
4       SSC      Retired    Islam       Married              3.0        1.0   

   BoyChild MonthlyEarning CancerType  CancerStage AdmittedHospital Operation  \
0       3.0           <10K       Anal          3.0              Yes       Yes   
1       0.0           <10K      Blood          1.0              Yes        No   
2       4.0           <10K     Throat          3.0              Yes        No   
3       NaN           <10K     Throat          NaN              Yes       Yes   
4       2.0           <10K      Lungs          3.0              Yes       Yes   

  FamilyMemberCancer FamMemSupport HospitalFeesPaymentIssue Loan  \
0                 No           Yes                Sometimes  Yes   
1                 No           Yes         Almost Regularly  Yes   
2                 No           Yes         Almost Regularly   No   
3                Yes           Yes                Regularly  Yes   
4                 No           Yes                Regularly  Yes   

  ElectronicDeviceforContact ElectronicDeviceType ContactDeviceWithDoctor  \
0                         No                  NaN              Not at all   
1                        Yes           Smartphone               Sometimes   
2                        Yes        Button Mobile              Not at all   
3                        Yes        Button Mobile              Not at all   
4                        Yes        Button Mobile               Sometimes   

  InternetAccess InternetUseExperience InternetUseForCancer  \
0             No         No Experience           Not at all   
1            Yes                Senior           Not at all   
2             No         No Experience           Not at all   
3             No         No Experience           Not at all   
4             No         No Experience           Not at all   

     DataCollectedBy                     PHQ1                     PHQ2  \
0  Zuhair + Mrittika               Not at all  More than half the days   
1              Miami            Several\ndays        Nearly\nevery day   
2           Mrittika        Nearly\nevery day            Several\ndays   
3              Miami        Nearly\nevery day        Nearly\nevery day   
4             Zuhair  More than half the days  More than half the days   

                      PHQ3                     PHQ4                     PHQ5  \
0        Nearly\nevery day        Nearly\nevery day        Nearly\nevery day   
1               Not at all        Nearly\nevery day  More than half the days   
2            Several\ndays        Nearly\nevery day               Not at all   
3        Nearly\nevery day               Not at all            Several\ndays   
4  More than half the days  More than half the days        Nearly\nevery day   

                      PHQ6                     PHQ7                     PHQ8  \
0  More than half the days  More than half the days  More than half the days   
1        Nearly\nevery day        Nearly\nevery day        Nearly\nevery day   
2               Not at all               Not at all               Not at all   
3  More than half the days  More than half the days            Several\nday

#Encoding Categorical values


In [92]:
df = df.drop(['PatientName'], axis=1)

In [93]:
df['DataCollectionPlace'].unique()

array(['Hospitals Doctor Chamber', 'Hospital Ward'], dtype=object)

In [94]:
df['DataCollectionPlace'] = df['DataCollectionPlace'].map({'Hospitals Doctor Chamber': 1, 'Hospital Ward':2})
print(df.DataCollectionPlace.unique())

[1 2]


In [95]:
df['Age'].unique()

array(['65+', '45-64', '25-44', '15-24'], dtype=object)

In [96]:
df['Age'] = df['Age'].map({'15-24': 1, '25-44':2, '45-64':3,'65+':4})
print(df.Age.unique())

[4 3 2 1]


In [97]:
df['Gender'].unique()

array(['Male', 'Female'], dtype=object)

In [98]:
df['Gender'] = df['Gender'].map({'Male': 1, 'Female':2})
print(df.Gender.unique())

[1 2]


In [99]:
df['CurrentAddress'].unique()

array(['Kishoregonj', 'Jhalokathi', 'Tangail', nan, 'Cumilla',
       'Gopalgonj', 'Jhinaidah', 'Barisal', 'Narayanginj', 'Dhaka',
       'Bogura', 'Feni', 'Sylhet', 'Tongi', 'Dinajpur', 'Thakurgaon',
       'Nilfamari', 'Rangamati', 'Pabna', 'Noakhali', 'Bhola', 'Jamalpur',
       'Narail', 'Kurigram', 'Chittagong', "Cox's Bazar", 'Mymensingh'],
      dtype=object)

In [100]:
df['Education'].unique()

array(['<SSC', 'SSC', 'HSC', 'Bachelor', 'Diploma', 'Ph.D', 'Masters'],
      dtype=object)

In [101]:
df['Education'] = df['Education'].map({'<SSC': 1, 'SSC':2, 'HSC':3,'Bachelor':4 ,'Diploma':5,'Ph.D':6,'Masters':7})
print(df.Education.unique())

[1 2 3 4 5 6 7]


In [102]:
df['Profession'].unique()

array(['Farmer', 'Shop Keeper', 'House Works', 'CNG Driver', 'Retired',
       'Small Business', 'House Wife', 'House WIfe', 'Teacher', 'Student',
       'E-Commerce Businessman', 'Job Holder', 'Day Labour', 'Banker',
       'Government Job', 'Business', 'Defense'], dtype=object)

In [103]:
df['Profession'] = df['Profession'].map({'Farmer': 1, 'Shop Keeper':2, 'House Works':3,'CNG Driver':4 ,'Retired':5,'Small Business':6,
                                         'House Wife':7, 'Teacher':8, 'Student':9,'E-Commerce Businessman':10, 'Business':10,'Job Holder':11,
                                         'Day Labour':12, 'Banker':13, 'Government Job':14, 'Defense':15})
print(df.Education.unique())

[1 2 3 4 5 6 7]


In [104]:
df['Religion'].unique()

array(['Islam'], dtype=object)

In [105]:
df['Religion'] = df['Religion'].map({'Islam': 1})
print(df.Religion.unique())

[1]


In [106]:
df['MaritalStatus'].unique()

array(['Married', 'Widowed', 'Unmarried', 'Divorced'], dtype=object)

In [107]:
df['MaritalStatus'] = df['MaritalStatus'].map({'Married': 1, 'Unmarried':2, 'Widowed':3, 'Divorced':4})
print(df.MaritalStatus.unique())

[1 3 2 4]


In [108]:
# for instance dropping this current address column, may use for later purpose
df=df.drop(['CurrentAddress', 'DataCollectedBy'], axis=1)

In [109]:
df.head()

DataCollectionPlace  Age  Gender  Education  Profession  Religion  \
0                    1    4       1          1         1.0         1   
1                    1    4       1          2         2.0         1   
2                    1    3       1          1         3.0         1   
3                    1    2       1          1         4.0         1   
4                    2    3       1          2         5.0         1   

   MaritalStatus  TotalChildCount  GirlChild  BoyChild MonthlyEarning  \
0              1              4.0        1.0       3.0           <10K   
1              1              1.0        1.0       0.0           <10K   
2              3              5.0        1.0       4.0           <10K   
3              1              NaN        NaN       NaN           <10K   
4              1              3.0        1.0       2.0           <10K   

  CancerType  CancerStage AdmittedHospital Operation FamilyMemberCancer  \
0       Anal          3.0              Yes       Yes                 No   
1      Blood          1.0              Yes        No                 No   
2     Throat          3.0              Yes        No                 No   
3     Throat          NaN              Yes       Yes                Yes   
4      Lungs          3.0              Yes       Yes                 No   

  FamMemSupport HospitalFeesPaymentIssue Loan ElectronicDeviceforContact  \
0           Yes                Sometimes  Yes                         No   
1           Yes         Almost Regularly  Yes                        Yes   
2           Yes         Almost Regularly   No                        Yes   
3           Yes                Regularly  Yes                        Yes   
4           Yes                Regularly  Yes                        Yes   

  ElectronicDeviceType ContactDeviceWithDoctor InternetAccess  \
0                  NaN              Not at all             No   
1           Smartphone               Sometimes            Yes   
2        Button Mobile              Not at all             No   
3        Button Mobile              Not at all             No   
4        Button Mobile               Sometimes             No   

  InternetUseExperience InternetUseForCancer                     PHQ1  \
0         No Experience           Not at all               Not at all   
1                Senior           Not at all            Several\ndays   
2         No Experience           Not at all        Nearly\nevery day   
3         No Experience           Not at all        Nearly\nevery day   
4         No Experience           Not at all  More than half the days   

                      PHQ2                     PHQ3                     PHQ4  \
0  More than half the days        Nearly\nevery day        Nearly\nevery day   
1        Nearly\nevery day               Not at all        Nearly\nevery day   
2            Several\ndays            Several\ndays        Nearly\nevery day   
3        Nearly\nevery day        Nearly\nevery day               Not at all   
4  More than half the days  More than half the days  More than half the days   

                      PHQ5                     PHQ6                     PHQ7  \
0        Nearly\nevery day  More than half the days  More than half the days   
1  More than half the days        Nearly\nevery day        Nearly\nevery day   
2               Not at all               Not at all               Not at all   
3            Several\ndays  More than half the days  More than half the days   
4        Nearly\nevery day            Several\ndays  More than half the days   

                      PHQ8                     PHQ9        PHQ10  \
0  More than half the days            Several\ndays        Tough   
1        Nearly\nevery day               Not at all  Not Tougher   
2               Not at all               Not at all  Not Tougher   
3            Several\ndays  More than half the days  Not Tougher   
4  More than half the days               Not at all        Tough   

  PatientConfused OurP